### ISSUE TITLE
Missing formatting method

### ISSUE THREAD

**Issue by L0thric-HM** [EnvyWare/ForgeEconomies#39]
Huh, that could breaks some things...
https://github.com/EnvyWare/ForgeEconomies/blob/main/sponge/src/main/java/com/envyful/economies/sponge/bridge/registry/ForgeCurrency.java#L37

**Comment by danorris709** [comment]
Do you have a crash report?

**Comment by L0thric-HM** [comment]
I particularly faced the problem when trying to use it with the original GTS. We already fixed on our side, but this was the situation we found when trying to add a new listing:
https://pastebin.com/smW6pvMR

**Comment by danorris709** [comment]
Okay well that stack trace originates from elsewhere. I also don't intend on supporting 1.12.2 currently
